name: goods_admin
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0
dependencies:
  animated_splash_screen: ^1.3.0
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.0.0
  cloud_functions: ^6.0.2
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  file_picker: ^10.3.1
  firebase_app_check: ^0.4.0
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  firebase_core_web: ^3.0.0
  firebase_messaging: ^16.0.1
  firebase_storage: ^13.0.2
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.3
  flutter_localization: ^0.3.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  hive: ^2.2.3
  image_cropper: ^11.0.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  lottie: ^3.3.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^12.0.1
  photo_view: ^0.15.0
  share_plus: ^12.0.0
  skeletonizer: ^2.0.1
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/splash_animation.json

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-VariableFont_slnt,wght.ttf
          weight: 700
flutter_launcher_icons:
  android: true
  image_path: "assets/images/app_icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_screen.png
  android: true
  android_gravity: fill
